version: "3"

services:
  api:
    build: .
    ports:
      - "8000:8000"
    command: uvicorn api.main:app --host=0.0.0.0 --port=8000
    volumes:
      - "./api:/app/api:delegated"
    healthcheck:
      test: python -c "import requests; requests.get('http://0.0.0.0:8000/api/health/')"
      interval: 1m
      timeout: 5s
